import type { Metadata } from "next";
import { Geist, Mr_De_Haviland } from "next/font/google";
import "./globals.css";
import { Navbar } from "../components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const havilandCursive = Mr_De_Haviland({
  variable: "--font-haviland-cursive",
  style: "normal",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${havilandCursive.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-900">
        <Navbar />
        <main className="grow container mx-auto px-2 py-4 md:px-4 md:py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
